# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkstyle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Checkstlye
      run: mvn -B checkstyle:checkstyle
    - name: Upload Checkstlye report
      uses: actions/upload-artifact@v2
      with:
        name: checkstyle-report
        path: target/checkstyle-result.xml
        retention-days: 2

  spotbugs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Spotbugs
      run: mvn -B spotbugs:spotbugs
    - name: Upload Spotbugs report
      uses: actions/upload-artifact@v2
      with:
        name: spotbugs-report
        path: ${{ project.build.directory }}/spotbugs.xml
        retention-days: 2

  jacoco:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Run Jacoco Report goal
          run: mvn -B jacoco:report
        - name: Upload Spotbugs report
          uses: actions/upload-artifact@v2
          with:
            name: jacoco-report
            path: ${{ project.reporting.outputDirectory }}/jacoco/index.html
            retention-days: 2
